### ISSUE TITLE
Android, v4: Could not invoke RNGCRemoteMediaClient.loadMedia

### ISSUE THREAD

**Issue by joeyscarim** [react-native-google-cast/react-native-google-cast#175]
**Describe the bug**
I am using the v4 branch, following the `example` and `playground` examples.
I detailed my setup instructions here: https://github.com/joeyscarim/react-native-cheatsheet#-chromecast

On iOS I have no issues: cast button -> connect to chromecast -> loadMedia working.
On Android, I can: cast button -> connect to chromecast -> but get an error when I trigger loadMedia:

![Screen Shot 2020-02-13 at 3 52 54 PM](https://user-images.githubusercontent.com/13211414/74485846-ea2bc300-4e78-11ea-8e16-bd527a5d67ac.png)

My javascript looks like this (just setup this way for testing):
```
           <CastButton style={{width: 24, height: 24}} />
            <TouchableOpacity
              onPress={() => {
                RemoteMediaClient.getCurrent().loadMedia(
                    {
                      contentUrl:
                        'https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/BigBuckBunny.mp4',
                      metadata: {
                        images: [
                          {
                            url:
                              'https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/images/480x270/BigBuckBunny.jpg',
                            width: 480,
                            height: 270,
                          },
                          {
                            url:
                              'https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/images/480x270/BigBuckBunny.jpg',
                            width: 780,
                            height: 1200,
                          },
                        ],
                        subtitle:
                          'A large and lovable rabbit deals with three tiny bullies, led by a flying squirrel, who are determined to squelch his happiness.',
                        title: 'Big Buck Bunny',
                        type: 'movie',
                      },
                      streamDuration: 596,
                    },
                    {autoplay: true},
                  )
                  .then(console.log)
                  .catch(console.warn);
              }}>
              <Text>CAST!</Text>
            </TouchableOpacity>

```

my adb log is as follows:
```
02-13 13:01:22.191 14636 14641 I zygote64: Do partial code cache collection, code=250KB, data=148KB
02-13 13:01:22.192 14636 14641 I zygote64: After code cache collection, code=250KB, data=148KB
02-13 13:01:22.192 14636 14641 I zygote64: Increasing code cache capacity to 1024KB
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: Exception in native call
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: java.lang.RuntimeException: Could not invoke RNGCRemoteMediaClient.loadMedia
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:790)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:164)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:764)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: Caused by: java.lang.reflect.InvocationTargetException
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	... 8 more
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: Caused by: java.lang.StackOverflowError: stack size 1037KB
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getReactApplicationContext(RNGCRemoteMediaClient.java:191)
02-13 13:01:22.195 14636 14668 E unknown:ReactNative: 	at com.reactnative.googlecast.api.RNGCRemoteMediaClient$10.getR
02-13 13:01:22.253 14636 14636 D ReactNative: CatalystInstanceImpl.destroy() start
02-13 13:01:22.257 14636 14636 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
02-13 13:01:22.269 14636 14636 W unknown:ReactNative: Tried to enqueue runnable on already finished thread: 'js... dropping Runnable.
02-13 13:01:22.271 14636 14636 W MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {bafbbd7} sending message to a Handler on a dead thread
02-13 13:01:22.271 14636 14636 W MessageQueue: java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {bafbbd7} sending message to a Handler on a dead thread
```

**Versions:**
- RNGC Library Version: v4
- Android Version (if applicable): 8.1.0
- OS Version (if applicable): 13.1

Any guidance would be greatly appreciated.  Cheers!

**Comment by joeyscarim** [comment]
switched to v3 instead and was able to get it working following the readme
