### ISSUE TITLE
[ANDROID] DynamiteModule$LoadingException: Failed to get module context

### ISSUE THREAD

**Issue by PauloMello99** [react-native-google-cast/react-native-google-cast#194]
**Describe the bug**
I collected this error from the Firebase Crashlytics attached to my app. Apparently the line 445 of the GoogleCastModule.java throws an error of null context. I was not able to reproduce the error on a physical or emulated device.

**Versions:**
- RNGC Library Version: 3.3.0
- Android Version: 28/29

**Devices**
- Samsung
  - Galaxy Tab S3
  - Galaxy S9
- Motorola
  - Moto G(7) Play

**Crash Log**
Fatal Exception: java.lang.RuntimeException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: Remote load failed. No local fallback found.
       at com.google.android.gms.internal.cast.zzae.zzg(com.google.android.gms:play-services-cast-framework@@18.1.0:51)
       at com.google.android.gms.internal.cast.zzae.zza(com.google.android.gms:play-services-cast-framework@@18.1.0:1)
       at com.google.android.gms.cast.framework.CastContext.<init>(com.google.android.gms:play-services-cast-framework@@18.1.0:39)
       at com.google.android.gms.cast.framework.CastContext.getSharedInstance(com.google.android.gms:play-services-cast-framework@@18.1.0:6)
       at com.reactnative.googlecast.GoogleCastModule$14.run(GoogleCastModule.java:445)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6923)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

Caused by com.google.android.gms.dynamite.DynamiteModule$LoadingException: Remote load failed. No local fallback found.
       at com.google.android.gms.dynamite.DynamiteModule.load(com.google.android.gms:play-services-basement@@17.1.0:32)
       at com.google.android.gms.internal.cast.zzae.zzg(com.google.android.gms:play-services-cast-framework@@18.1.0:41)
       at com.google.android.gms.internal.cast.zzae.zza(com.google.android.gms:play-services-cast-framework@@18.1.0:1)
       at com.google.android.gms.cast.framework.CastContext.<init>(com.google.android.gms:play-services-cast-framework@@18.1.0:39)
       at com.google.android.gms.cast.framework.CastContext.getSharedInstance(com.google.android.gms:play-services-cast-framework@@18.1.0:6)
       at com.reactnative.googlecast.GoogleCastModule$14.run(GoogleCastModule.java:445)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6923)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
Caused by com.google.android.gms.dynamite.DynamiteModule$LoadingException: Failed to get module context
       at com.google.android.gms.dynamite.DynamiteModule.zzb(com.google.android.gms:play-services-basement@@17.1.0:237)
       at com.google.android.gms.dynamite.DynamiteModule.zza(com.google.android.gms:play-services-basement@@17.1.0:162)
       at com.google.android.gms.dynamite.DynamiteModule.load(com.google.android.gms:play-services-basement@@17.1.0:16)
       at com.google.android.gms.internal.cast.zzae.zzg(com.google.android.gms:play-services-cast-framework@@18.1.0:41)
       at com.google.android.gms.internal.cast.zzae.zza(com.google.android.gms:play-services-cast-framework@@18.1.0:1)
       at com.google.android.gms.cast.framework.CastContext.<init>(com.google.android.gms:play-services-cast-framework@@18.1.0:39)
       at com.google.android.gms.cast.framework.CastContext.getSharedInstance(com.google.android.gms:play-services-cast-framework@@18.1.0:6)
       at com.reactnative.googlecast.GoogleCastModule$14.run(GoogleCastModule.java:445)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6923)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

**Comment by petrbela** [comment]
I haven't seen this. Feel free to reopen if you manage to reproduce this.

**Comment by YangJonghun** [comment]
Hi @petrbela 

I hope you reopen this issue

I think this issue related with Google Play Service version and Google Play Service update state. so very hard to reproduce

I know you already mentioned only about installation within your docs (TroubleShoot section), but I think Fatal Exception also occurred when version conflict with Cast SDK version

so, if you can, please use guard method every time when you call

`CastContext.getSharedInstance(context);`

FYI)
- I think PR #367 couldn't prevent this issue. it can prevent only when app launch. sometimes Play Service automatically update when user use our app. it think it may occur crash also

my opinion based on below links
- https://stackoverflow.com/questions/42765632/runtimeexception-chromecast
- https://stackoverflow.com/questions/46052983/detecting-googleplayservices-availability-does-not-work
links are quite old, but until recently my app's Crashlytics report show me some sort of device was frequently affected

**Comment by petrbela** [comment]
This should now be handled properly in v4.4.0. You can even prompt the user to install Play Services https://react-native-google-cast.github.io/docs/getting-started/usage#android-handle-missing-google-play-services

**Comment by yedidyak** [comment]
Somehow I am still getting this occasionally only on some Samsung devices on Android 11. Does anyone maybe know of a Samsung bug or missing check that could explain that?
