### ISSUE TITLE
[android crash] App crashing while connecting to casting device in android.

### ISSUE THREAD

**Issue by dasDeepankar** [react-native-google-cast/react-native-google-cast#286]
System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 511.00 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 23, 25, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 

**Error Log** 

 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/HasApiKey;
        at com.google.android.gms.internal.cast.zzae.zza(com.google.android.gms:play-services-cast-framework@@19.0.0:2)
        at com.google.android.gms.cast.framework.CastSession.zzd(com.google.android.gms:play-services-cast-framework@@19.0.0:90)
        at com.google.android.gms.cast.framework.CastSession.start(com.google.android.gms:play-services-cast-framework@@19.0.0:15)
        at com.google.android.gms.cast.framework.Session$zza.start(com.google.android.gms:play-services-cast-framework@@19.0.0:6)
        at com.google.android.gms.cast.framework.zzac.zza(com.google.android.gms:play-services-cast-framework@@19.0.0:17)
        at com.google.android.gms.internal.cast.zza.onTransact(com.google.android.gms:play-services-cast@@19.0.0:13)
        at android.os.Binder.transact(Binder.java:1043)
        at ke.P(:com.google.android.gms.dynamite_dynamitemodulesc@205016097@20.50.16 (150400-0):2)
        at rj.h(:com.google.android.gms.dynamite_dynamitemodulesc@205016097@20.50.16 (150400-0):0)
        at rt.m(:com.google.android.gms.dynamite_dynamitemodulesc@205016097@20.50.16 (150400-0):14)
        at se.d(:com.google.android.gms.dynamite_dynamitemodulesc@205016097@20.50.16 (150400-0):3)
        at sc.a(:com.google.android.gms.dynamite_dynamitemodulesc@205016097@20.50.16 (150400-0):3)
        at kf.onTransact(:com.google.android.gms.dynamite_dynamitemodulesc@205016097@20.50.16 (150400-0):4)
        at android.os.Binder.transact(Binder.java:1043)
        at com.google.android.gms.internal.cast.zzb.zzb(com.google.android.gms:play-services-cast@@19.0.0:21)
        at com.google.android.gms.internal.cast.zzal.zzd(com.google.android.gms:play-services-cast-framework@@19.0.0:21)
        at com.google.android.gms.internal.cast.zzaw.onRouteSelected(com.google.android.gms:play-services-cast-framework@@19.0.0:4)
        at androidx.mediarouter.media.MediaRouter$GlobalMediaRouter$CallbackHandler.invokeCallback(MediaRouter.java:2992)
        at androidx.mediarouter.media.MediaRouter$GlobalMediaRouter$CallbackHandler.handleMessage(MediaRouter.java:2942)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.HasApiKey" on path: DexPathList[[zip file "/data/app/~~7ltV41YHoyzfVZDfXoGkWQ==/com.skillsoft.Percipio-5HRifXUjkZ-n7FJKBeqYDw==/base.apk"],nativeLibraryDirectories=[/data/app/~~7ltV41YHoyzfVZDfXoGkWQ==/com.skillsoft.Percipio-5HRifXUjkZ-n7FJKBeqYDw==/lib/arm64, /data/app/~~7ltV41YHoyzfVZDfXoGkWQ==/com.skillsoft.Percipio-5HRifXUjkZ-n7FJKBeqYDw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]

**Comment by petrbela** [comment]
That looks like Google Play Services are not available. See the first item in [Troubleshooting](https://react-native-google-cast.github.io/docs/getting-started/troubleshooting)

**Comment by dasDeepankar** [comment]
@petrbela i have checked google play services are there in my device. but still this crash is occurring  with an error **Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.HasApiKey**. not sure why it's happening. need a help here!

**Comment by jona-laa** [comment]
Was this ever resolved? Having the same issue...

**Comment by petrbela** [comment]
@jona-laa What versions are you using? From what I understand, the error means the Play Services library is either missing or of an old version.

**Comment by jona-laa** [comment]
@petrbela Umm... I'm using react-native-google-cast ^4.6.0. Play service library version, I'm not sure. Where can I get this info? Everything used to work fine until recently, so it's kind of weird.
