### ISSUE TITLE
Error log java.lang.NoSuchMethodError: No static method

### ISSUE THREAD

**Issue by ajaysaini-sgvu** [react-native-google-cast/react-native-google-cast#331]
Hello Team, We are using this plugin for one of the project. When our application is launching then `GoogleCast` component is breaking with below error when we use `appcompat` library in android.  `com.android.support:appcompat-v7:28.0.0`

```

java.lang.NoSuchMethodError: No static method saveAttributeDataForStyleable(Landroid/view/View;Landroid/content/Context;[ILandroid/util/AttributeSet;Landroid/content/res/TypedArray;II)V in class Landroidx/core/view/ViewCompat; or its super classes (declaration of 'androidx.core.view.ViewCompat' appears in /data/app/com.usablenet.mobile.walgreen.staging-WAWlgortMzHbuEIJFQ3IzQ==/base.apk!classes11.dex)
at androidx.mediarouter.app.MediaRouteButton.<init>(MediaRouteButton.java:159)
at androidx.mediarouter.app.MediaRouteButton.<init>(MediaRouteButton.java:151)
at androidx.mediarouter.app.MediaRouteButton.<init>(MediaRouteButton.java:147)
at com.reactnative.googlecast.components.RNGoogleCastButtonManager$ColorableMediaRouteButton.<init>(RNGoogleCastButtonManager.java:82)
at com.reactnative.googlecast.components.RNGoogleCastButtonManager.createViewInstance(RNGoogleCastButtonManager.java:45)
at com.reactnative.googlecast.components.RNGoogleCastButtonManager.createViewInstance(RNGoogleCastButtonManager.java:23)
```

Can you pls look into it ?

**Comment by petrbela** [comment]
Hi! I can't help much without having a full code example to debug.

However, it seems like an Android version compatibility with the Android Cast SDK, not this React Native library, so you might be able to get help in the official Google Cast forums.
