### ISSUE TITLE
Crash Unable to start service MediaNotificationService

### ISSUE THREAD

**Issue by Marzdor** [react-native-google-cast/react-native-google-cast#447]
I am not sure when exactly this crash has started but, it is happening whenever I try casting to a chrome-cast device. Once I click a device to cast to it instantly crashes the app and the only error I see is the one below. I have not yet been able to see a similar issue with this but this seems to be the service it is talking about [MediaNotificationService](https://developers.google.com/android/reference/com/google/android/gms/cast/framework/media/MediaNotificationService
)

I was using version 4.1.2 but even updating to 4.4.1 I see the same issue.

This only happens on Android

Update: seems that my app's old build through that apk works fine, but if I build that version from source I see the crash. This makes me think that something with the build flow brakes it. 

Update 2: 
Okay I believe that the apk version might be pointing too `castFrameworkVersion = "21.0.0"` or older, since we were setting it to just use the latest version at the time. 
However, when I now build it from source now it is pointing to `castFrameworkVersion = "21.1.0"` since that is now the latest. When I manually set it too `castFrameworkVersion = "21.0.0"` and build the crash no longer shows and it works fine.

With that something in the `21.1.0` version is breaking 

```
08-23 08:58:58.950  2499  2499 E AndroidRuntime: FATAL EXCEPTION: main
08-23 08:58:58.950  2499  2499 E AndroidRuntime: Process: com.app, PID: 2499
08-23 08:58:58.950  2499  2499 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.google.android.gms.cast.framework.media.MediaNotificationService@19696d1 with Intent { act=com.google.android.gms.cast.framework.action.UPDATE_NOTIFICATION pkg=com.app cmp=com.app/com.google.android.gms.cast.framework.media.MediaNotificationService (has extras) }: java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.app/com.reactnative.googlecast.RNGCExpandedControllerActivity}
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5110)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at android.app.ActivityThread.access$2200(ActivityThread.java:310)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8669)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.app/com.reactnative.googlecast.RNGCExpandedControllerActivity}
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at androidx.core.app.TaskStackBuilder.addParentStack(TaskStackBuilder.java:210)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at androidx.core.app.TaskStackBuilder.addNextIntentWithParentStack(TaskStackBuilder.java:144)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at com.google.android.gms.cast.framework.media.MediaNotificationService.zzh(com.google.android.gms:play-services-cast-framework@@21.1.0:16)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at com.google.android.gms.cast.framework.media.MediaNotificationService.onStartCommand(com.google.android.gms:play-services-cast-framework@@21.1.0:15)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	... 9 more
08-23 08:58:58.950  2499  2499 E AndroidRuntime: Caused by: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.app/com.reactnative.googlecast.RNGCExpandedControllerActivity}
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:597)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at androidx.core.app.NavUtils.getParentActivityName(NavUtils.java:261)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at androidx.core.app.NavUtils.getParentActivityIntent(NavUtils.java:195)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	at androidx.core.app.TaskStackBuilder.addParentStack(TaskStackBuilder.java:203)
08-23 08:58:58.950  2499  2499 E AndroidRuntime: 	... 13 more
```

**Comment by petrbela** [comment]
Hmm, there has been some change to the notification service in 21.1.0; I'll try to investigate where the problem might be.

**Comment by tbarusseau** [comment]
I have the same issue, I'll try updating to the latest version of the library.

**Comment by petrbela** [comment]
@tbarusseau Setting `castFrameworkVersion = "21.0.0"` should work (the change was made in `21.1.0` onwards and hasn't been addressed yet)

**Comment by tbarusseau** [comment]
@petrbela Wow! I've never had such a fast response. Just updating the dependency and rebuilding doesn't fix the issue - I'll clean the android build cache and try a full new build.
