### ISSUE TITLE
Android 12 crash

### ISSUE THREAD

**Issue by mezalejandro** [react-native-google-cast/react-native-google-cast#466]
**Describe the bug**
When chromecast is connected with the mobile, it's crash immediately

<img width="821" alt="Screen Shot 2022-11-14 at 12 53 19" src="https://user-images.githubusercontent.com/568141/201705062-dd0bb3d2-47a3-43dd-9186-edbcc6d584a4.png">

I've  ^4.5.0 version installed.
Thanks

**Comment by petrbela** [comment]
Can you please post the whole stack trace, along with steps to reproduce? Thanks

**Comment by CHaNGeTe** [comment]
`Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                                    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                                    	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
                                                                                                    	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:651)
                                                                                                    	at android.app.PendingIntent.getBroadcast(PendingIntent.java:638)
                                                                                                    	at com.google.android.gms.cast.framework.media.internal.zzm.zza(com.google.android.gms:play-services-cast-framework@@19.0.0:46)
                                                                                                    	at com.google.android.gms.cast.framework.CastSession$zza.onResult(com.google.android.gms:play-services-cast-framework@@19.0.0:11)
                                                                                                    	at com.google.android.gms.common.api.internal.BasePendingResult$CallbackHandler.handleMessage(com.google.android.gms:play-services-base@@17.1.0:11)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at com.google.android.gms.internal.base.zar.dispatchMessage(com.google.android.gms:play-services-base@@17.1.0:8)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:233)
                                                                                                    	at android.os.Looper.loop(Looper.java:344)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8204)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)`
                                                                                                    

To reproduce:
Just making click on Cast icon

**Comment by fdobre** [comment]
This crash ca be replicated in 4.6.2 too.

**Comment by swathim** [comment]
Has anyone found a solution for this crash? Please update us the fix if so.

**Comment by IvanSantiagoUk** [comment]
This still happening on latest version 4.6.2

Do we have a solution for this?
