### ISSUE TITLE
Crash "No castSession!" (should throw a promise error instead of a crash)

### ISSUE THREAD

**Issue by Minishlink** [react-native-google-cast/react-native-google-cast#477]
**Describe the bug**
Hello, this is a crash from our crash monitoring tool

```
Fatal Exception: java.lang.IllegalStateException: No castSession!
       at com.reactnative.googlecast.api.RNGCRemoteMediaClient$18.getX(RNGCRemoteMediaClient.java:285)
       at com.reactnative.googlecast.api.RNGCRemoteMediaClient$18.getX(RNGCRemoteMediaClient.java:277)
       at com.reactnative.googlecast.api.With$3.run(With.java:45)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**To Reproduce**
As it is a crash from our crash monitoring tool, I don't have the exact steps but it looks like users successfully casted a video to its completion prior the crash.

**Expected behavior**
The app should not crash. It should throw a promise error when fails. It might have a retry mechanism.

**Device:**
 - Devices: Huawei Honor 7X on Android 9, Samsung Galaxy S20 FE 5G on Android 13
 - Library Version: 4.6.1

**Checklist:**
 - [x] I have followed [Installation](https://react-native-google-cast.github.io/docs/getting-started/installation) and [Setup](https://react-native-google-cast.github.io/docs/getting-started/setup)
 - [x] My problem is not described in [Troubleshooting](https://react-native-google-cast.github.io/docs/getting-started/troubleshooting)
 - [x] I have searched [existing issues](https://github.com/react-native-google-cast/react-native-google-cast/issues?q=is%3Aissue) and have not found a similar one

**Comment by jedashford** [comment]
We have the same crash. We're trying to find a solution. 4700 unique users and 6K crashes over the past 30 days :(
`    "react-native-google-cast": "4.5.0",`

**Comment by Minishlink** [comment]
@jedashford Have you found any reproduction steps? I haven't myself yet

**Comment by petrbela** [comment]
I made a small change that I think was causing the crash. Can you retest with v4.6.2?

**Comment by Minishlink** [comment]
Thanks @petrbela, will update you once I have the data

**Comment by Minishlink** [comment]
Looks good, thanks! :)
