### ISSUE TITLE
[Android] Crash "LoadingException: No acceptable module" on host resume

### ISSUE THREAD

**Issue by Minishlink** [react-native-google-cast/react-native-google-cast#480]
**Describe the bug**
Hello, this is another crash from our crash monitoring tool

```
Fatal Exception: java.lang.RuntimeException: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
       at com.google.android.gms.cast.framework.CastContext.getSharedInstance(com.google.android.gms:play-services-cast-framework@@21.2.0:11)
       at com.reactnative.googlecast.api.RNGCCastContext$7.run(RNGCCastContext.java:195)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6823)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```

**To Reproduce**
As it is a crash from our crash monitoring tool, I don't have the exact steps but from what I gathered it may be because google play services is not available when this is run on host resume. This is surprising because there is a check just before, although it might become unavailable afterwards? Maybe it's simply because the google play services is not up to date.

**Expected behavior**
The app should not crash. It should send back the error to the JS somehow (an event ?). It might have a retry mechanism.

**Device:**
 - Devices: 97% samsung, 3% Oppo
 - Versions : 55% Android 7, 29% Android 13, Android 11, Android 12
 - Library Version: 4.6.1

**Checklist:**
 - [x] I have followed [Installation](https://react-native-google-cast.github.io/docs/getting-started/installation) and [Setup](https://react-native-google-cast.github.io/docs/getting-started/setup)
 - [x] My problem is not described in [Troubleshooting](https://react-native-google-cast.github.io/docs/getting-started/troubleshooting)
 - [x] I have searched [existing issues](https://github.com/react-native-google-cast/react-native-google-cast/issues?q=is%3Aissue) and have not found a similar one

**Comment by SufianBabri** [comment]
Yes, this is likely because of missing GMS. I am also seeing this on an emulator (one with no Google APIs) and in production it is reported for new Huawei devices (which have HMS instead).

At one point this library used to crash if no GMS was found, so [this comment](https://github.com/react-native-google-cast/react-native-google-cast/issues/287#issuecomment-779280700) talks about a possible fix. It was eventually fixed in the library with [this PR](https://github.com/react-native-google-cast/react-native-google-cast/pull/367). The crash still happens on my end when this like gets executed in my screen's cleanup (I am ending the casting session when the video player screen is closed):
```
GoogleCast.sessionManager.endCurrentSession(true);
```

I think some of the methods in the library will have to ignore the calls if the GMS isn't available or return an error in some way.

**Comment by SufianBabri** [comment]
According to [this comment](https://github.com/android/uamp/issues/97#issuecomment-253061870), it could be happening due to an outdated GMS version:

> Found a solution that worked for me. It's because either your device or emulator has an outdated version of Google Play services. Right above your error you should see something in the log cat that says
> 
> Google Play services out of date. Requires 3264100 but found 3225132
> 
> Just update the Google Play services and it'll work.

I downgraded the Google Player Services version to v17 (from v23 with which everything was working fine) but couldn't get Chromecasting to work. So I'm not sure what could be wrong.
