### ISSUE TITLE
Cast button disabled and greyed

### ISSUE THREAD

**Issue by samandarkuchkarov** [react-native-google-cast/react-native-google-cast#526]
**Describe the bug**
i do my code as showed documentation, i registered my receiver app in https://cast.google.com/  and i add 
Application ID to my mobile app, icon is showing buy greyed and can not click. and i find  this error

```
Unable to update local snapshot for com.google.android.gms.cast_dynamite#uz.comnet.tvcomstb, may result in stale flags.
java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=uz.comnet.tvcomstb, sha256=[9245793aef7479175c643c3a37b302e52ac65c2f7740bc68105527e69c2cb1f3], atk=false, ver=241518038.true (go/gsrlt)
  at m.czk.s(:com.google.android.gms.dynamite_dynamitemodulesc@241518038@24.15.18 (190400-0):21)
  at m.czk.get(:com.google.android.gms.dynamite_dynamitemodulesc@241518038@24.15.18 (190400-0):3)
  at m.dav.g(:com.google.android.gms.dynamite_dynamitemodulesc@241518038@24.15.18 (190400-0):8)
  at m.ciz.d(:com.google.android.gms.dynamite_dynamitemodulesc@241518038@24.15.18 (190400-0):1)
  at m.cir.run(:com.google.android.gms.dynamite_dynamitemodulesc@241518038@24.15.18 (190400-0):5)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
  at java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
  at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=uz.comnet.tvcomstb, sha256=[9245793aef7479175c643c3a37b302e52ac65c2f7740bc68105527e69c2cb1f3], atk=false, ver=241518038.true (go/gsrlt)
  at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
  at android.os.Parcel.createException(Parcel.java:2409)
  at android.os.Parcel.readException(Parcel.java:2392)
  at android.os.Parcel.readException(Parcel.java:2334)
  at m.aqg.c(:com.google.android.gms.dynamite_dynamitemodulesc@241518038@24.15.18 (190400-0):11)
  at m.bnq.a(:com.google.android.gms.dynamite_dynamitemodulesc@241518038@24.15.18 (190400-0):39)
  at m.bcd.e(:com.google.android.gms.dynamite_dynamitemodulesc@241518038@24.15.18 (190400-0):11)
  at m.bda.u(:com.google.android.gms.dynamite_dynamitemodulesc@241518038@24.15.18 (190400-0):10)
  at m.bda.v(:com.google.android.gms.dynamite_dynamitemodulesc@241518038@24.15.18 (190400-0):22)
  at m.bda.g(:com.google.android.gms.dynamite_dynamitemodulesc@241518038@24.15.18 (190400-0):30)
  at m.bda.h(:com.google.android.gms.dynamite_dynamitemodulesc@241518038@24.15.18 (190400-0):84)
  at m.bda.b(:com.google.android.gms.dynamite_dynamitemodulesc@241518038@24.15.18 (190400-0):15)
  at m.bej.c(:com.google.android.gms.dynamite_dynamitemodulesc@241518038@24.15.18 (190400-0):97)
  at m.bed.d(:com.google.android.gms.dynamite_dynamitemodulesc@241518038@24.15.18 (190400-0):7)
  at m.bee.handleMessage(:com.google.android.gms.dynamite_dynamitemodulesc@241518038@24.15.18 (190400-0):277)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loopOnce(Looper.java:201)
  at android.os.Looper.loop(Looper.java:288)
  at android.os.HandlerThread.run(HandlerThread.java:67)
```

--

<br class="Apple-interchange-newline">

**Device:**
 - Device: [Android]

 - Library Version [e.g. 4.x]

**Checklist:**
 - [X] I have followed [Installation](https://react-native-google-cast.github.io/docs/getting-started/installation) and [Setup](https://react-native-google-cast.github.io/docs/getting-started/setup)
 - [X] My problem is not described in [Troubleshooting](https://react-native-google-cast.github.io/docs/getting-started/troubleshooting)
 - [X] I believe the bug is in the React Native Google Cast library, not in the Google Cast SDK. Otherwise please use the official [Google Cast Support](https://developers.google.com/cast/support) as I'm not able to help with native SDK issues.
 - [X] I have searched [existing issues](https://github.com/react-native-google-cast/react-native-google-cast/issues?q=is%3Aissue) and have not found a similar one

**Comment by petrbela** [comment]
Hi, can you please create a repository that reproduces the issue?

**Comment by samandarkuchkarov** [comment]
Hi , it worked in real device, thank you
