### ISSUE TITLE
Fatal Exception on Android 14

### ISSUE THREAD

**Issue by mezalejandro** [react-native-google-cast/react-native-google-cast#527]
**Describe the bug**
in firebase I get this error:
Unable to start service com.google.android.gms.cast.framework.media.MediaNotificationService@c076495 with Intent { act=com.google.android.gms.cast.framework.action.UPDATE_NOTIFICATION

**Screenshots**
<img width="813" alt="Screenshot 2024-05-09 at 6 12 53 AM" src="https://github.com/react-native-google-cast/react-native-google-cast/assets/568141/c7425743-b7b5-40b0-83bc-2b2f193a063d">
<img width="1051" alt="Screenshot 2024-05-09 at 6 15 20 AM" src="https://github.com/react-native-google-cast/react-native-google-cast/assets/568141/9d91c8a0-10a1-4adb-81d1-6b7a255c37c4">

**Device:**
 - Device: Android
 - OS: Android 14
 - Library Version: 4.8.0

**Comment by bberak** [comment]
Notes sure if you found a fix for this @mezalejandro -- but I think this is going to affect all developers that are targeting Android SDK 34 due to a missing permission (`FOREGROUND_SERVICE_MEDIA_PLAYBACK`):

```
-------- beginning of crash
08-12 17:10:47.950 26971 26971 E AndroidRuntime: FATAL EXCEPTION: main
08-12 17:10:47.950 26971 26971 E AndroidRuntime: Process: com.myapp.myappplayerforandroid, PID: 26971
08-12 17:10:47.950 26971 26971 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.google.android.gms.cast.framework.media.MediaNotificationService@80fdf09 with Intent { act=com.google.android.gms.cast.framework.action.UPDATE_NOTIFICATION pkg=com.myapp.myappplayerforandroid cmp=com.myapp.myappplayerforandroid/com.google.android.gms.cast.framework.media.MediaNotificationService (has extras) }: java.lang.SecurityException: Starting FGS with type mediaPlayback callerApp=ProcessRecord{4107815 26971:com.myapp.myappplayerforandroid/u0a53} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK] 
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5286)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8934)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: Caused by: java.lang.SecurityException: Starting FGS with type mediaPlayback callerApp=ProcessRecord{4107815 26971:com.myapp.myappplayerforandroid/u0a53} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK] 
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3053)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3036)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2978)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7234)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at android.app.Service.startForeground(Service.java:775)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at com.google.android.gms.cast.framework.media.MediaNotificationService.zzj(com.google.android.gms:play-services-cast-framework@@20.1.0:29)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at com.google.android.gms.cast.framework.media.MediaNotificationService.onStartCommand(com.google.android.gms:play-services-cast-framework@@20.1.0:14)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	... 9 more
08-12 17:10:47.950 26971 26971 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at com.android.server.am.ActiveServices.validateForegroundServiceType(ActiveServices.java:2741)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2452)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1797)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:15948)
08-12 17:10:47.950 26971 26971 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact$setServiceForeground$(IActivityManager.java:11974)
```

**Comment by bberak** [comment]
For others who encounter this problem, I believe you need to list the following permissions in your `AndroidManifest.xml` file.

```
FOREGROUND_SERVICE'
FOREGROUND_SERVICE_MEDIA_PLAYBACK
```

**Comment by mezalejandro** [comment]
Hello @bberak, yes I've these two permission in my manifest

**Comment by petrbela** [comment]
Please update to the latest version of this library and create a new issue if you run into any problems.
